package com.PTW.testscripts;


import java.io.IOException;
import java.util.Iterator;
//import java.util.List;
import java.util.Set;

//import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;


import com.PTW.generic.BaseClass2;
import com.PTW.generic.FileLib;
import com.PTW.pom.LifeCycle;
import com.PTW.pom.SignInPage;
import com.aventstack.extentreports.Status;

public class ApprovalLifeCycle extends BaseClass2{


	@Test

	public void testApprovalLifeCycle() throws InterruptedException, IOException {
		FileLib f = new FileLib();
		String user = f.getProperty("user");
		String password = f.getProperty("password");
		SignInPage sip = new SignInPage(driver);
		testCase = extentReport.createTest("Mail Id Text Box");
		sip.getusernameTextbox().sendKeys(user);
		testCase.log(Status.INFO, "usernameTextbox Field ");
		testCase.log(Status.PASS, "Valid mail id Enter Successfully ");
		System.out.println("User Name Successfully Enter");
		Thread.sleep(2000);
		sip.getpasswordTextbox().sendKeys(password);
		testCase = extentReport.createTest("Password Text Box");
		testCase.log(Status.INFO, "usernameTextbox Field ");
		testCase.log(Status.PASS, "Valid password Enter Successfully ");
		System.out.println("Password  Successfully Enter");
		Thread.sleep(2000);
		sip.getloginButton().click();
		testCase = extentReport.createTest("Login Button Field");
		testCase.log(Status.INFO, "usernameTextbox Field ");
		testCase.log(Status.PASS, "Login Button Clicks Successfully ");
		System.out.println("Login Successfully ");

		LifeCycle lc = new LifeCycle(driver);
		SoftAssert sat = new SoftAssert();
		lc.getpermitvision().click();
		testCase = extentReport.createTest("permitvision Button Field");
		testCase.log(Status.INFO, "permitvision Field ");
		testCase.log(Status.PASS, "Permit Visible Successfully ");
		System.out.println("Permit Visible Successfully");
		Thread.sleep(2000);
		
		lc.getpermittowork().click();
		testCase = extentReport.createTest("Permit-work Visible ");
		testCase.log(Status.INFO, "Permit-work Visible Field ");
		testCase.log(Status.PASS, "Permit-work Visible Successfully ");
		System.out.println("Permit-work Visible Successfully");
		Thread.sleep(2000);
		
		lc.getrequested().click();
		testCase = extentReport.createTest("Permit-work Request  Field ");
		testCase.log(Status.INFO, "Permit-work Request Field ");
		testCase.log(Status.PASS, "Permit-work Request Successfully Enter ");
		System.out.println("Permit-work Requested Successfully");
		Thread.sleep(2000);
		lc.getGeneral().click();
		Thread.sleep(2000);
		testCase = extentReport.createTest("Permit-work Request  Field ");
		testCase.log(Status.INFO, "Navigate to Permit Vision - Permit to Work - Requested. ");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state.");
		System.out.println("permit successfully submitted to Reviewed");
		lc.getactionpage().click();  
		testCase = extentReport.createTest("\\\"Action Page\\\" tab ");
		testCase.log(Status.INFO, "Select Permit with no ICC attached and click \"Action Page\" tab AA/AAF.");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state AA/AAF.");
		System.out.println("permit successfully submitted to Reviewed");
		Thread.sleep(2000);
		lc.getreviewpermit().click();
		testCase = extentReport.createTest("Review Permit by AA/AAF");
		testCase.log(Status.INFO, "Click \"Review Permit by AA/AAF\".");
		testCase.log(Status.PASS, "Permit successfully submitted to \"Reviewed\"AA/AAF.");
		System.out.println("Permit successfully submitted to \"Reviewed\"AA/AAF.");
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button in Signatures section.");
		testCase.log(Status.PASS, "Permit Icon is a triangle.");
		System.out.println("Permit Icon is a triangle.");
		Thread.sleep(2000);
		lc.getclicktocontinu().click();
		Thread.sleep(2000);
		lc.getactionpage().click();
		testCase = extentReport.createTest("\\\"Action Page\\\" tab ");
		testCase.log(Status.INFO, "Select Permit with no ICC attached and click \"Action Page\" tab PIC.");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state PIC.");
		System.out.println("permit successfully submitted to Reviewed");
		Thread.sleep(2000);
		lc.getendrosepermit().click();
		testCase = extentReport.createTest("Endorse Permit by PIC.");
		testCase.log(Status.INFO, "Click \"Endorse Permit by PIC\".");
		testCase.log(Status.PASS, "Permit Icon is a diamond with an \"E\" inside.");
		System.out.println("Permit Icon is a diamond with an \"E\" inside.");
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button in Signatures section.");
		testCase.log(Status.PASS, "Permit Icon is a diamond with an \\\"E\\\" inside.");
		System.out.println("Permit Icon is a diamond with an \\\"E\\\" inside.");
		Thread.sleep(2000);
		lc.getclicktocontinu().click();
		Thread.sleep(2000);
		lc.getactionpage().click();
		Thread.sleep(2000);

		lc.getAttachments().click();
		Thread.sleep(2000);
		lc.getbtnAddAttachment().click();
		Thread.sleep(2000);
		lc.gettemporarydefeatcertificate().click();
		Thread.sleep(4000);
		lc.getnextlabel().click();
		Thread.sleep(2000);
		lc.getactionpage().click();
		testCase = extentReport.createTest("\\\"Action Page\\\" tab ");
		testCase.log(Status.INFO, "Navigate to the \"Action Page\" tab. \"Action Page\" tab  AA.");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state AA.");
		System.out.println("permit successfully submitted to Reviewed");
		Thread.sleep(2000);
		lc.getauthorizepermit().click();
		testCase = extentReport.createTest("Authorize Permit by AA");
		testCase.log(Status.INFO, "Click \"Authorize Permit by AA\".");
		testCase.log(Status.PASS, "Permit successfully submitted to \"Authorized\".");
		System.out.println("Permit successfully submitted to \"Authorized\".");
		Thread.sleep(2000);

		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button in Signatures section.");
		testCase.log(Status.PASS, "Authorized Permit Icon is a diamond ");
		System.out.println("Authorized Permit Icon is a diamond ");
		Thread.sleep(2000);
		lc.getclicktocontinu().click();
		Thread.sleep(2000);
		lc.getactionpage().click();
		testCase = extentReport.createTest("\\\"Action Page\\\" tab ");
		testCase.log(Status.INFO, "Navigate to the \"Action Page\" tab. \"Action Page\" tab  AO.");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state AO.");
		System.out.println("permit successfully submitted to Reviewed");
		Thread.sleep(2000);
		lc.getpermitbyAO().click();
		testCase = extentReport.createTest("Issue Permit by AO");
		testCase.log(Status.INFO, "Click \"Issue Permit by AO\".");
		testCase.log(Status.PASS, "Permit successfully submitted to \"Issued\".");
		System.out.println("Permit successfully submitted to \"Issued\".");
		Thread.sleep(2000);
		lc.getsignAO().click();
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button in Signatures section.");
		testCase.log(Status.PASS, "Permit Icon is a triangle with an \"I\" inside.");
		System.out.println("Permit Icon is a triangle with an \"I\" inside.");
		Thread.sleep(2000);
		lc.getclicktocontinu().click();
		Thread.sleep(2000);
		lc.getactionpage().click();
		testCase = extentReport.createTest("\\\"Action Page\\\" tab ");
		testCase.log(Status.INFO, "Navigate to the \"Action Page\" tab. \"Action Page\" tab  PH.");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state PH.");
		System.out.println("permit successfully submitted to Reviewed");
		Thread.sleep(2000);
		lc.getpermitbyph().click();   //noted
		testCase = extentReport.createTest("Accept Permit by PH");
		testCase.log(Status.INFO, "Click \"Accept Permit by PH\".");
		testCase.log(Status.PASS, "Permit successfully submitted to \"Live\".");
		System.out.println("Permit successfully submitted to \"Live\".");
		Thread.sleep(2000);
		lc.getsignAO().click();
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button in Signatures section.");
		testCase.log(Status.PASS, "Permit Icon is a squarePermit prints successfully");
		System.out.println("Permit Icon is a squarePermit prints successfully");
		Thread.sleep(3000);
		Set<String> windows = driver.getWindowHandles();
		Iterator<String> it = windows.iterator();
		String st = it.next();
		String child = it.next();
		driver.switchTo().window(child);
		Thread.sleep(10000);
		driver.close();
		driver.switchTo().window(st);

		Thread.sleep(2000);
		lc.getclicktocontinu().click();
		Thread.sleep(2000);
		lc.getactionpage().click();
		testCase = extentReport.createTest("\\\"Action Page\\\" tab ");
		testCase.log(Status.INFO, "Navigate to the \"Action Page\" tab. \"Action Page\" tab.");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state.");
		System.out.println("permit successfully submitted to Reviewed");
		Thread.sleep(2000);
		lc.getjobcomplete().click();
		Thread.sleep(2000);
		lc.getjobcompleterdbtn().click();
		testCase = extentReport.createTest("Job Complete ");
		testCase.log(Status.INFO, "Click \"Job Complete or Job Incomplete by PH/AA/AAF/AO\" under \"Possilbe Actions\" section.");
		testCase.log(Status.INFO, "Job Incomplete Signature pop-up box appears with the following");
		testCase.log(Status.PASS, "I confirm that all personnel have been accounted for and the worksite has been restored to a safe and tidy working condition.");
		testCase.log(Status.PASS, "A comments field that has an orange asterisk, signifying required field.");
		System.out.println("I confirm that all personnel have been accounted for and the worksite has been restored to a safe and tidy working condition");
		Thread.sleep(2000);
		lc.getjobsign().click();
		Thread.sleep(2000);
		lc.getjobrdobtn().click();
		testCase = extentReport.createTest("\"Yes\" on the attestation radio button.");
		testCase.log(Status.INFO, "Click \"Yes\" on the attestation radio button.");
		testCase.log(Status.PASS, "Permit successfully submitted to \"Job Incomplete\"");
		System.out.println("Permit successfully submitted to \"Job Incomplete\"");
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button in Signatures section.");
		testCase.log(Status.PASS, "Permit icon is a pentagon with an \"I\" inside");
		System.out.println("Permit icon is a pentagon with an \"I\" inside");
		Thread.sleep(2000);
		lc.getclicktocontinu().click();
		Thread.sleep(2000);
		lc.getactionpage().click();
		testCase = extentReport.createTest("\\\"Action Page\\\" tab ");
		testCase.log(Status.INFO, "Navigate to the \"Action Page\" tab. \"Action Page\" tab.");
		testCase.log(Status.PASS, "Requested screen appears with permits that are in that state PTW by AO.");
		System.out.println("permit successfully submitted to Reviewed PTW by AO");
		Thread.sleep(2000);
		lc.getptwbyAO().click();
		testCase = extentReport.createTest("PTW Complete by AO");
		testCase.log(Status.INFO, "PTW Complete signature pop-up box appears with an attestatio that says \"I am satisfied that the worksite has been restored to a safe and tidy condition");
		testCase.log(Status.PASS, "I have updated the AA of the status/progress of the job");
		System.out.println("I have updated the AA of the status/progress of the job");
		Thread.sleep(2000);
		lc.getjobsign().click();
		Thread.sleep(2000);
		lc.getjobrdobtn().click();
		testCase = extentReport.createTest("\"Yes\" on the attestation radio button.");
		testCase.log(Status.INFO, "Click \"Yes\" on the attestation radio button.");
		testCase.log(Status.PASS, "Permit successfully submitted to \"PTW Complete\".");
		System.out.println("Permit successfully submitted to \"PTW Complete\".");
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button in Signatures section.");
		testCase.log(Status.PASS, "Permit icon is a hexagon.");
		System.out.println("Permit icon is a hexagon.");
		Thread.sleep(2000);
		lc.getarchivepermit().click();
		testCase = extentReport.createTest("\"Sign\" next to the \"Validate Lessons Learned by AA/AAF\" signature");
		testCase.log(Status.INFO, "Validate Lessons Learned by AA/AAF\\\" signature");
		testCase.log(Status.PASS, "Validate Lessons Learned by \"AA/AAF\" pop up box appears with an attestation that says \"Did you review the lessons and delete any lessons that aren't valid?\".");
		System.out.println("Validate Lessons Learned by \\\"AA/AAF\\\" pop up box appears");
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "\"Archive Permit by PIC/PC/AA/AO/AAF/PH\" ");
		testCase.log(Status.PASS, "Permit is successfully submitted to \"Archived\".");
		System.out.println("Permit is successfully submitted to \"Archived\".");
		Thread.sleep(2000);
		lc.getpermit2work().click();
		
		Thread.sleep(2000);
		lc.getback2main().click();
		Thread.sleep(2000);
		lc.getsearchicon().click();
		testCase = extentReport.createTest("Navigate to Permit to Work - Search.");
		testCase.log(Status.INFO, "Permit to Work - Search.");
		testCase.log(Status.PASS, "Archived Permits appear on search screen.");
		System.out.println("Archived Permits appear on search screen.");
		Thread.sleep(2000);
		lc.getdropdownicon().click();
		Thread.sleep(2000);
		lc.getArchived().click();
		testCase = extentReport.createTest("Change \"Status\" filter to \"Archived\"");
		testCase.log(Status.INFO, "Change \"Status\" filter to \"Archived\"");
		testCase.log(Status.PASS, "Permit icon is a hexagon with an \"A\" inside");
		System.out.println("Permit icon is a hexagon with an \"A\" inside");
		Thread.sleep(2000);
		lc.getDeletedbtn().click();
		Thread.sleep(2000);
		lc.getsearchbtn().click();
		testCase = extentReport.createTest("Click on archived permit.");
		testCase.log(Status.INFO, "Change \"Status\" filter to \"Archived\"");
		testCase.log(Status.PASS, "Job Incomplete reason appears next to the signature.");
		System.out.println("Job Incomplete reason appears next to the signature.");
		Thread.sleep(2000);
		String pwh=driver.getWindowHandle();
		lc.getshmtest().click();
		Thread.sleep(2000);

		Set<String> handles = driver.getWindowHandles();
		for (String newWindow : handles) {
			if(!newWindow.equals(pwh))
			{
				driver.switchTo().window(newWindow);	
			}
		}

		lc.getstep7().click();
		testCase = extentReport.createTest("Navigate to \"Details Page\" and click step 7");
		testCase.log(Status.INFO, "Navigate to Details Page");
		testCase.log(Status.PASS, "Navigate to Details Page Successfully");
		System.out.println("Navigate to Details Page Successfully");
		Thread.sleep(2000);
		lc.getaddlesson().click();
		testCase = extentReport.createTest("\"Add Lesson Learned\" button and add a new lesson to the permit.");
		testCase.log(Status.INFO, "\\\"Add Lesson Learned\\\" button");
		testCase.log(Status.PASS, "Initial lesson is deleted New lesson added to permit and showing in the \"Lessons Learned\" section");
		System.out.println("Navigate to Details Page Successfully");
		
		Thread.sleep(2000);
		String lessonDescription = f.getProperty("lessonDescription");
		lc.getlessonDescription().sendKeys(lessonDescription);
		Thread.sleep(2000);
		lc.getokbtndes().click();
		Thread.sleep(2000);
		lc.getsigndesc().click();
		testCase = extentReport.createTest("\"Sign\" next to the \"Validate Lessons Learned by AA/AAF\" signature in the Signatures section.");
		testCase.log(Status.INFO, "Validate Lessons Learned by AA/AAF\\");
		testCase.log(Status.PASS, "Validate Lessons Learned by \"AA/AAF\" pop up box appears with an attestation that says \"Did you review the lessons and delete any lessons that aren't valid?\".");
		System.out.println("Validate Lessons Learned by \"AA/AAF\" pop up box appears with an attestation that says \"Did you review the lessons and delete any lessons that aren't valid?\".");
		Thread.sleep(2000);
		lc.getyesradio().click();
		Thread.sleep(2000);
		lc.getloggedin().click();
		testCase = extentReport.createTest("Sign as logged in");
		testCase.log(Status.INFO, "Click \"Sign as logged in\" button");
		testCase.log(Status.PASS, "Signature successfully added to the permit.");
		System.out.println("Signature successfully added to the permit.");
		Thread.sleep(2000);
		driver.close();
		Thread.sleep(2000);
		driver.switchTo().window(pwh);
		Thread.sleep(3000);

		lc.getusernamebtn().click();
		Thread.sleep(4000);
		lc.getlogout().click();
		testCase = extentReport.createTest("Logout");
		testCase.log(Status.INFO, "Click \" logged off\" button");
		testCase.log(Status.PASS, "Logout Successfully");
		System.out.println("Logout Successfully");
		Thread.sleep(4000);
		driver.quit();

	}
}
